### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by dbreaker** [Scripted/wordpress-plugin#1]
Our pagination is not working.  We think this is an issue with the scripted API, but if you could investigate and report back in this issue that'd be helpful.

![2018-07-27 at 2 30 pm](https://user-images.githubusercontent.com/24713/43342811-aa941112-91a9-11e8-8682-1dc5af5c557b.png)

When you do that, you get this screen instead of the other posts:
![2018-07-27 at 2 31 pm](https://user-images.githubusercontent.com/24713/43342843-c3418c9e-91a9-11e8-85f7-2eda72a08326.png)

**Comment by dbreaker** [comment]
you can use these keys to test.  this is a real account, so don't do anything destructive.

b99fa011
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoyLCJwYXJ0eV9rZXkiOiI3YjY2ZTQwMCIsImV4cCI6MTYyNDI5OTcxNCwibG9uZ19saXZlZCI6dHJ1ZSwiaWF0IjoxNTI5NjA1MzE0fQ.bJDG_uI0jIJWQ2QIdY-U19CBJk5bzOZEWPsl8ctgYSw

**Comment by jmanzo** [comment]
Hi Doug, I have some questions about this ticket. How can I add more jobs to the list? I need to do this because I want to test deeply with the pagination.

**Comment by dbreaker** [comment]
@jmanzo, unfortunately you can't, that's a production account.

Here's another account that has a bunch more jobs:

c1b866a0

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoyLCJwYXJ0eV9rZXkiOiI0MmJlNjRkOCIsImV4cCI6MTYyNzkzODk2MywibG9uZ19saXZlZCI6dHJ1ZSwiaWF0IjoxNTMzMjQ0NTYzfQ.l-Zp82r92osJib4fwVD0SaeunIeA3EU7uHmr-7y-s9o

**Comment by jmanzo** [comment]
I don't understand something. There's resources that are not accesible for the plugin. Look at this: http://prntscr.com/kerm4s

It seems like the repo is not completed. Could you check if there's another version or if it is up to date on the repo? Thank you

**Comment by dbreaker** [comment]
@stevenmaguire thoughts here?  That code is referencing scripted.test?

**Comment by jmanzo** [comment]
yes, it is referencing because I am developing/checking in my local enviroment. The thing is that there're stuffs that seems doesn't appear in someway in this repo. Is this the original repo?

**Comment by stevenmaguire** [comment]
After having a look around, I am not entirely sure what is happening here. This is the only repo under our control on GH for the wordpress plugin. 

A quick google search does uncover another (different?) SVN repo associated with the published plugin on WordPress' website. Perhaps, that is the one that is being installed? 

https://wordpress.org/plugins/scripted-api/

@jmanzo can you please do a bit deeper investigation on this and let us know your thoughts/findings? Are we barking up the wrong tree with this GH repo?

**Comment by jmanzo** [comment]
The error was in the route in the line #56 on the pagination. It was `scripted_current_jobs/`, I changed to `scripted_jobs/`
